### ISSUE TITLE
why did you remove the JSON quick fix for things that don't return JSON?

### ISSUE THREAD

**Issue by krokodaxl** [appoxy/mini_fb#61]
quick fix for things like stream.publish that don't return json
```
res_hash = JSON.parse("{\"response\": #{resp.to_s}}")
```

**Comment by treeder** [comment]
Good question...

**Comment by blanchma** [comment]
@krokodaxl as soon as merged will be fixed. My fault.

**Comment by treeder** [comment]
It's already merged @blanchma

**Comment by treeder** [comment]
Oh, just saw #62

**Comment by treeder** [comment]
@krokodaxl can you verify this is fixed with 2.2.1

**Comment by blanchma** [comment]
@treeder BTW there's a discrepancy between the version in lib/VERSION and the one published in rubygems. I guess we should update the lib/VERSION to match it.

**Comment by treeder** [comment]
oh, thought I deleted VERSION file
